# Window
window:
  dimensions:
    columns: 140
    lines: 38
  decorations: none
scrolling:
  history: 10000
  multiplier: 3
# background_opacity: 0.95
window.dynamic_title: true
    
# Cursor
cursor:
  style: Block

# Font
font:
  normal:
    family: "JetBrainsMono Nerd Font"
    style: Regular

  bold:
    family: "JetBrainsMono Nerd Font"
    style: Bold

  italic:
    family: "JetBrainsMono Nerd Font"
    style: Italic

  bold_italic:
    family: "JetBrainsMono Nerd Font"
    style: Bold Italic

  size: 10

# Schemes
schemes:
  onedark: &onedark
    primary:
      background: '0x1e2127'
      foreground: '0xabb2bf'
      #dim_foreground: '0x9a9a9a'
      bright_foreground: '0xe6efff'
    #cursor:
    #  text: '0x000000'
    #  cursor: '0xffffff'
    normal:
      black:   '0x1e2127'
      red:     '0xe06c75'
      green:   '0x98c379'
      yellow:  '0xd19a66'
      blue:    '0x61afef'
      magenta: '0xc678dd'
      cyan:    '0x56b6c2'
      white:   '0x828791'
    bright:
      black:   '0x5c6370'
      red:     '0xe06c75'
      green:   '0x98c379'
      yellow:  '0xd19a66'
      blue:    '0x61afef'
      magenta: '0xc678dd'
      cyan:    '0x56b6c2'
      white:   '0xe6efff'
    dim:
      black:   '0x1e2127'
      red:     '0xe06c75'
      green:   '0x98c379'
      yellow:  '0xd19a66'
      blue:    '0x61afef'
      magenta: '0xc678dd'
      cyan:    '0x56b6c2'
      white:   '0x828791'
  nord: &nord
    primary:
      background: '#2e3440'
      foreground: '#d8dee9'
      dim_foreground: '#a5abb6'
    cursor:
      text: '#2e3440'
      cursor: '#d8dee9'
    vi_mode_cursor:
      text: '#2e3440'
      cursor: '#d8dee9'
    selection:
      text: CellForeground
      background: '#4c566a'
    search:
      matches:
        foreground: CellBackground
        background: '#88c0d0'
      footer_bar:
        background: '#434c5e'
        foreground: '#d8dee9'
    normal:
      black: '#3b4252'
      red: '#bf616a'
      green: '#a3be8c'
      yellow: '#ebcb8b'
      blue: '#81a1c1'
      magenta: '#b48ead'
      cyan: '#88c0d0'
      white: '#e5e9f0'
    bright:
      black: '#4c566a'
      red: '#bf616a'
      green: '#a3be8c'
      yellow: '#ebcb8b'
      blue: '#81a1c1'
      magenta: '#b48ead'
      cyan: '#8fbcbb'
      white: '#eceff4'
    dim:
      black: '#373e4d'
      red: '#94545d'
      green: '#809575'
      yellow: '#b29e75'
      blue: '#68809a'
      magenta: '#8c738c'
      cyan: '#6d96a5'
      white: '#aeb3bb'
  github_nord: &github_nord
    primary:
      background: '#22272e'
      foreground: '#adbac7'
      dim_foreground: '#a5abb6'
    cursor:
      text: '#2e3440'
      cursor: '#d8dee9'
    vi_mode_cursor:
      text: '#2e3440'
      cursor: '#d8dee9'
    selection:
      text: CellForeground
      background: '#4c566a'
    search:
      matches:
        foreground: CellBackground
        background: '#88c0d0'
      footer_bar:
        background: '#434c5e'
        foreground: '#d8dee9'
    normal:
      black: '#3b4252'
      red: '#bf616a'
      green: '#a3be8c'
      yellow: '#ebcb8b'
      blue: '#81a1c1'
      magenta: '#b48ead'
      cyan: '#88c0d0'
      white: '#e5e9f0'
    bright:
      black: '#4c566a'
      red: '#bf616a'
      green: '#a3be8c'
      yellow: '#ebcb8b'
      blue: '#81a1c1'
      magenta: '#b48ead'
      cyan: '#8fbcbb'
      white: '#eceff4'
    dim:
      black: '#373e4d'
      red: '#94545d'
      green: '#809575'
      yellow: '#b29e75'
      blue: '#68809a'
      magenta: '#8c738c'
      cyan: '#6d96a5'
      white: '#aeb3bb'
  github_dimmed: &github_dimmed
    primary:
      background: '#22272e'
      # foreground: '#768390'
      foreground: '#adbac7'
      dim_foreground: '#a5abb6'
    normal:
      black:   '#545d68'
      red:     '#f47067'
      green:   '#57ab5a'
      yellow:  '#c69026'
      blue:    '#539bf5'
      magenta: '#b083f0'
      cyan:    '#39c5cf'
      white:   '#909dab'
    bright:
      black:   '#636e7b'
      red:     '#ff938a'
      green:   '#6bc46d'
      yellow:  '#daaa3f'
      blue:    '#6cb6ff'
      magenta: '#dcbdfb'
      cyan:    '#56d4dd'
      white:   '#cdd9e5'

    indexed_colors:
      - { index: 16, color: '#d18616' }
      - { index: 17, color: '#ff938a' }
  github_dark: &github_dark
    primary:
      background: '#24292e'
      foreground: '#d1d5da'
    normal:
      black:   '#586069'
      red:     '#ea4a5a'
      green:   '#34d058'
      yellow:  '#ffea7f'
      blue:    '#2188ff'
      magenta: '#b392f0'
      cyan:    '#39c5cf'
      white:   '#d1d5da'
    bright:
      black:   '#959da5'
      red:     '#f97583'
      green:   '#85e89d'
      yellow:  '#ffea7f'
      blue:    '#79b8ff'
      magenta: '#b392f0'
      cyan:    '#56d4dd'
      white:   '#fafbfc'

    indexed_colors:
      - { index: 16, color: '#d18616' }
      - { index: 17, color: '#f97583' }

# Color
colors: *github_nord

