[window]
decorations = "none"
dynamic_title = true

dimensions.columns = 140
dimensions.lines = 38

[scrolling]
history = 10000
multiplier = 3

[font]
size = 10

normal.family = "JetBrainsMono Nerd Font"
normal.style = "Regular"

bold.family = "JetBrainsMono Nerd Font"
bold.style = "Bold"

italic.family = "JetBrainsMono Nerd Font"
italic.style = "Italic"

bold_italic.family = "JetBrainsMono Nerd Font"
bold_italic.style = "Bold Italic"

[cursor]
style = "Block"

[colors]
primary.background = "#22272e"
primary.dim_foreground = "#a5abb6"
primary.foreground = "#adbac7"

cursor.cursor = "#d8dee9"
cursor.text = "#2e3440"

vi_mode_cursor.cursor = "#d8dee9"
vi_mode_cursor.text = "#2e3440"

search.matches.background = "#88c0d0"
search.matches.foreground = "CellBackground"

footer_bar.background = "#434c5e"
footer_bar.foreground = "#d8dee9"

selection.background = "#4c566a"
selection.text = "CellForeground"

normal.black = "#3b4252"
normal.blue = "#81a1c1"
normal.cyan = "#88c0d0"
normal.green = "#a3be8c"
normal.magenta = "#b48ead"
normal.red = "#bf616a"
normal.white = "#e5e9f0"
normal.yellow = "#ebcb8b"

bright.black = "#4c566a"
bright.blue = "#81a1c1"
bright.cyan = "#8fbcbb"
bright.green = "#a3be8c"
bright.magenta = "#b48ead"
bright.red = "#bf616a"
bright.white = "#eceff4"
bright.yellow = "#ebcb8b"

dim.black = "#373e4d"
dim.blue = "#68809a"
dim.cyan = "#6d96a5"
dim.green = "#809575"
dim.magenta = "#8c738c"
dim.red = "#94545d"
dim.white = "#aeb3bb"
dim.yellow = "#b29e75"
