#!/bin/sh

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Assign workspaces to specific monitor
# workspace 8 output eDP-1
# workspace 9 output eDP-1

# Configs
bspc config border_width 0
bspc config window_gap 15
bspc config split_ratio 0.6
bspc config borderless_monocle true
bspc config gapless_monocle true
bspc config focused_border_color "#D8DEE9"
bspc config normal_border_color "#3B4252"

# Rules
bspc rule -a feh state=floating
bspc rule -a Thunar -a thunar state=floating
bspc rule -a barrier state=floating
bspc rule -a mpv state=floating

# Autostart
killall -u $USER -q sxhkd; sxhkd 2>&1 | tee "/tmp/sxhkd-$USER.log" & disown
killall -u $USER -q picom; picom --experimental-backend 2>&1 | tee -a "/tmp/picom-$USER.log" & disown
killall -u $USER -q dunst; dunst 2>&1 | tee "/tmp/dunst-$USER.log" & disown
killall -u $USER -q polybar; polybar top 2>&1 | tee "/tmp/polybar-$USER.log" & disown

feh --bg-fill -z -r "$HOME/Pictures/wallpapers" &

# start ibus-daemon for hangul input
ibus-daemon -drxR

