#!/bin/sh

# Autostart
killall -q sxhkd; sxhkd &
killall -q picom; picom --experimental-backend &
killall -q dunst; dunst &

feh --bg-fill -z -r "$HOME/Pictures/wallpapers" &

# Workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# Assign workspaces to specific monitor
# workspace 8 output eDP-1
# workspace 9 output eDP-1

# Configs
bspc config border_width         0
bspc config window_gap           15
#bspc config top_padding  20

bspc config split_ratio          0.52
bspc config border_radius        20
bspc config gapless_monocle      true
bspc config borderless_monocle   true

# Rules
# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Firefox desktop='^2'
# bspc rule -a mpv state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

bspc rule -a feh state=floating
# bspc rule -a sxiv state=floating
bspc rule -a mpv state=floating

